---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prometheus-demo-service-monitor
  labels:
    app: spring-prometheus-demo
    release: stable
spec:
  selector:
    matchLabels:
      app: spring-prometheus-demo
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"