server:
  port: ${app.container.port}

spring:
  application:
    name: demo

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    migrate-legacy-ids: true
    web:
      exposure:
        include: "health,metrics,env,prometheus,refresh"

